Add installation options.
habitat-sh/on-prem-builder pull request #261
Opened 2022-04-27 17:52 UTC by dikshagupta1

Builder-HA: Enable users to install postgresql and minio separately

2022-04-28 13:37 UTC, pozsgaic commented on scripts/provision.sh
> +  if sudo hab svc status habitat/builder-api >/dev/null 2>/dev/null; then
We don't want to have sudo embedded in a script.  It is better to invoke sudo at the cmd line,

2022-04-28 22:13 UTC, mwrock commented on scripts/provision.sh
>    --generate-bootstrap   Generate a bootstrap to be used for scaling our API Frontends
This isn't related to this change but while you are here, could you delete this line? We removed the `--generate-bootstrap` functionality but did not remove this doc note.

2022-04-28 22:38 UTC, mwrock requested changes

2022-04-28 22:38 UTC, mwrock commented on scripts/provision.sh
> +  start_datastore
Similar to `start_builder` you will need to add:

```
    while [ ! -f /hab/svc/builder-datastore/config/pwfile ]
    do
      sleep 2
    done
    local pg_pass=$(cat /hab/svc/builder-datastore/config/pwfile)
    cat <<EOT > pg_pass.toml
[datastore]
password = "$pg_pass"
EOT
  hab config apply builder-api.default $(date +%s) pg_pass.toml
```
Probably want to extract that to its own function.

2022-04-28 22:38 UTC, mwrock commented on scripts/provision.sh
> +  configure
need to call `init_datastore` before `start_datastore`

2022-04-29 12:12 UTC, pozsgaic commented on scripts/provision.sh
> +  if sudo hab svc status habitat/builder-api >/dev/null 2>/dev/null; then
Ignore the above - we have been using sudo in this script and have it wrapped in a function.

2022-05-05 00:51 UTC, mwrock approved these changes

2022-05-05 06:07 UTC, merged